# Maximum width of each line
max_width = 80

# Use tab characters for indentation, spaces for alignment
hard_tabs = true

# Replace uses of the try! macro by the ? shorthand
use_try_shorthand = true

# Use field initialize shorthand if possible.
use_field_init_shorthand = true

### UNSTABLE FEATURES

# Convert /* */ comments to // comments where possible
normalize_comments = true

# Put a trailing comma after a block based match arm (non-block arms are not affected)
match_block_trailing_comma = true

# Item layout inside a imports block
imports_layout = "Vertical"

# Error if unable to get all lines within max_width
error_on_line_overflow = false

# Merge multiple imports into a single nested import.
merge_imports = true

# Reorder impl items. type and const are put first, then macros and methods.
reorder_impl_items = true
